### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by fanbu1995** [OHDSI/CohortExplorer#11]
It seems that this package requires R 4.1.0+ instead of R 3.6.0+. Also, could you please consider managing the dependencies using `renv`?

**Comment by gowthamrao** [comment]
i have no problem going to 3.6.0+ (i am no expert ) - have you tested if the package works on 3.6.0?

regarding renv - i think i have renv for the shiny that is part of its output - see here https://github.com/OHDSI/CohortExplorer/tree/main/inst/shiny/renv

is that what you are referring to?

**Comment by fanbu1995** [comment]
I think the common version across OHDSI packages is something close to 4.0.5? My guess is that the package may still work -- I can look into it and follow up with you. 

I'm hoping that this package itself also uses renv to manage dependencies (not just the generated shinyApp directory). That allows for easier local configuration, but of course not absolutely necessary.

**Comment by schuemie** [comment]
HADES packages cannot use renv, for the same reason that CRAN packages cannot use renv: if you want to install two packages with conflicting renv lock files, what should you do? CohortExplorer, like any other HADES package, will work with the current released versions of its dependencies.

A Shiny app *can* use renv, which in this case it does, to make sure the Shiny app keeps working when newer versions of packages are released

**Comment by schuemie** [comment]
The minimum required R version for HADES in R 4.0.0, because ParallelLogger requires this (because it uses the error handling framework introduced in R 4.0.0)

**Comment by gowthamrao** [comment]
Ok - that implies going lower than 4.0.0 would make no difference as ParallelLogger wont install. CohortExplorer does not require 4+ (i think) but its dependencies do. 

I will lower to 4.0.0
