### ISSUE TITLE
ShinyApp data table "Days To First" column

### ISSUE THREAD

**Issue by fanbu1995** [OHDSI/CohortExplorer#12]
The "Days to First" column in the data table seems to run search through a text match (say, when I search for "0" it doesn't return 0 days only, but also any day that has a "0" in the string). Perhaps we want a numeric match for search in this column. 

Further, "Days to First" seems to be calculated reversely --- e.g., with an index date of 2017-01-01, the day of 2016-12-30 would be 2 days to first, but perhaps we want it to be -2. 

See attached screenshot for a reference. 

<img width="206" alt="Screen Shot 2023-01-05 at 11 25 14 AM" src="https://user-images.githubusercontent.com/31320024/210863843-3d997c77-2e84-416b-a1e2-a23b6f087dc3.png">

**Comment by gowthamrao** [comment]
Regarding being reversed - i can see it being confusing. a negative number would be AFTER day 0, and positive number would be BEFORE day 0. Others have told me that it is confusing. Happy to change it (just dont know whats is better).

Regarding 
> Perhaps we want a numeric match for search in this column.

Yea - that enhancement would make sense, i think i just have the default react table functionality. Is it a simple change (i dont know)

**Comment by fanbu1995** [comment]
Oh I see! Would probably be better if after day 0 is positive -- at least that's what I feel. 

It shouldn't be hard to search using numeric match; possibly all it's needed is to convert that column to "double" or "integer" type for searching.

**Comment by gowthamrao** [comment]
Yea - it probably needs from reactable acrobatics - which i dont know how to do :) So if anyone wants to do a PR, i will keep it as is
