### ISSUE TITLE
Final message provides incorrect path

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortExplorer#15]
The message generated [here](https://github.com/OHDSI/CohortExplorer/blob/main/R/CreateCohortExplorerApp.R#L1026) points to a 'CohortExplorer' subfolder, but in fact it is called 'CohortExplorerShiny'

**Comment by schuemie** [comment]
In fact, why does the function create a subfolder called 'CohortExplorerShiny'? Why not just put the Shiny app in the `exportFolder` itself?

**Comment by gowthamrao** [comment]
This change is fine by me
