### ISSUE TITLE
Misleading file extension

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortExplorer#17]
The file in the '/data' folder has an '.Rdata' extension as defined [here](https://github.com/OHDSI/CohortExplorer/blob/main/R/CreateCohortExplorerApp.R#L225), but is saved using `saveRDS()` so should have and '.rds' extension

**Comment by gowthamrao** [comment]
Are you recommending we change it? I am fine doing the change. Also, i dont think there is a need to ensure backward compatibility as these output are not meant to be persisted.

What do you think about changing it but not ensuring backward compatibility with pervious .Rdata

**Comment by schuemie** [comment]
I don't see an issue with changing it. The Shiny app would actually work regardless of what the extension is (because it uses list.files)
