### ISSUE TITLE
Migrate to dbplyr when ready

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortExplorer#9]
See comment here https://github.com/OHDSI/DatabaseConnector/issues/35#issuecomment-1317187179

**Comment by schuemie** [comment]
Why would you migrate to `dbplyr`? Your code seems to work fine, right?

**Comment by gowthamrao** [comment]
Ooh - ok - i thought there was going to be some dbplyr related important changes that needs to be considered - based on the above referenced discussion. Closing this issue
